name: Static Analysis

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  static-analysis:
    uses: marinade-finance/.github/.github/workflows/static-analysis.yml@main
    with:
      rust-workspace:       ${{ vars.STATIC_ANALYSIS_RUST_WORKSPACE       || '.' }}
      anchor-workspace:     ${{ vars.STATIC_ANALYSIS_ANCHOR_WORKSPACE     || '' }}
      anchor-programs-path: ${{ vars.STATIC_ANALYSIS_ANCHOR_PROGRAMS_PATH || '' }}
      run-rust:             ${{ vars.STATIC_ANALYSIS_RUN_RUST             || 'auto' }}
      run-solana:           ${{ vars.STATIC_ANALYSIS_RUN_SOLANA           || 'auto' }}
      anchor-cli-version:   ${{ vars.STATIC_ANALYSIS_ANCHOR_CLI_VERSION   || '0.31.1' }}
      clippy-deny-warnings: ${{ vars.STATIC_ANALYSIS_CLIPPY_DENY_WARNINGS != 'false' }}
