name: Trivy - Scan

on:
  pull_request:
  merge_group:

jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Run Trivy scanner - generate report
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: 'mirror.gcr.io/aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db'
          TRIVY_JAVA_DB_REPOSITORY: 'mirror.gcr.io/aquasec/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db'
        with:
          scan-type: fs
          format: table
          scan-ref: .
          hide-progress: false
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo '```'
              cat trivy.txt
              echo '```'
            } >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run Trivy scanner - Fail on Critical
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: 'mirror.gcr.io/aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db'
          TRIVY_JAVA_DB_REPOSITORY: 'mirror.gcr.io/aquasec/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db'
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
        with:
          scan-type: fs
          format: table
          scan-ref: .
          hide-progress: false
          output: trivy.txt
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: 1
          skip-setup-trivy: true
